"""
Route file export — KML 2.2 and GPX 1.1.

Generates two chart-plotter-friendly route files from passage waypoints:
  - {Route_Name}_Route.kml — Google Earth, Google My Maps, OpenCPN
  - {Route_Name}_Route.gpx — Garmin / B&G / Raymarine plotters, Navionics

The filename uses underscores so it stays safe across file systems and
URL-encoded sharing.

Public API:
  write_kml(passage, output_path) -> str
  write_gpx(passage, output_path) -> str
  write_route_files(passage, output_dir) -> (kml_path, gpx_path)
"""
import os
from datetime import datetime, timezone
from xml.sax.saxutils import escape as xml_escape


def _route_name_for_files(passage: dict) -> str:
    """Build a filesystem-safe route name from passage metadata.

    E.g. 'Charleston-Beaufort' -> 'Charleston-Beaufort'
    """
    name = passage["passage"]["name"]
    # Replace spaces and slashes with underscores; keep dashes
    safe = name.replace(" ", "_").replace("/", "_").replace("\\", "_")
    return safe


def write_kml(passage: dict, output_path: str) -> str:
    """Write a KML 2.2 route file. Returns the path.

    The KML contains:
      - <Document> with name and description
      - One <Placemark> per waypoint as a Point (so they show as labeled pins)
      - One <Placemark> with a <LineString> connecting all WPs in order
    """
    waypoints = passage["waypoints"]
    route_name = passage["passage"]["name"]
    origin = passage["passage"].get("origin", "")
    dest = passage["passage"].get("destination", "")
    total_nm = passage["passage"].get("total_nm", 0)

    parts = ['<?xml version="1.0" encoding="UTF-8"?>']
    parts.append('<kml xmlns="http://www.opengis.net/kml/2.2">')
    parts.append('<Document>')
    parts.append(f'  <name>{xml_escape(route_name)} Route</name>')
    parts.append(
        f'  <description>{xml_escape(origin)} → {xml_escape(dest)} '
        f'({total_nm:.0f} NM). Generated by sailbuild.</description>'
    )

    # Style for waypoint pins
    parts.append('  <Style id="wp_style">')
    parts.append('    <IconStyle>')
    parts.append('      <color>ff0080ff</color>')   # orange
    parts.append('      <scale>0.9</scale>')
    parts.append('      <Icon><href>http://maps.google.com/mapfiles/kml/shapes/sailing.png</href></Icon>')
    parts.append('    </IconStyle>')
    parts.append('    <LabelStyle><scale>0.9</scale></LabelStyle>')
    parts.append('  </Style>')

    # Style for the route line
    parts.append('  <Style id="route_style">')
    parts.append('    <LineStyle>')
    parts.append('      <color>ffff0000</color>')   # blue (kml BGR)
    parts.append('      <width>3</width>')
    parts.append('    </LineStyle>')
    parts.append('  </Style>')

    # Waypoint placemarks
    for wp in waypoints:
        wp_id = wp.get("id", "")
        wp_name = wp.get("name", "")
        cum_nm = wp.get("cum_nm", 0)
        lat = wp["lat"]
        lon = wp["lon"]
        parts.append('  <Placemark>')
        parts.append(f'    <name>{xml_escape(wp_id)} — {xml_escape(wp_name)}</name>')
        parts.append(
            f'    <description>{xml_escape(wp_name)}\nCum: {cum_nm:.1f} NM'
            f'\nLat: {lat:.4f}, Lon: {lon:.4f}</description>'
        )
        parts.append('    <styleUrl>#wp_style</styleUrl>')
        parts.append('    <Point>')
        parts.append(f'      <coordinates>{lon:.6f},{lat:.6f},0</coordinates>')
        parts.append('    </Point>')
        parts.append('  </Placemark>')

    # Route line
    parts.append('  <Placemark>')
    parts.append(f'    <name>{xml_escape(route_name)} Route Line</name>')
    parts.append('    <styleUrl>#route_style</styleUrl>')
    parts.append('    <LineString>')
    parts.append('      <tessellate>1</tessellate>')
    parts.append('      <coordinates>')
    for wp in waypoints:
        parts.append(f'        {wp["lon"]:.6f},{wp["lat"]:.6f},0')
    parts.append('      </coordinates>')
    parts.append('    </LineString>')
    parts.append('  </Placemark>')

    parts.append('</Document>')
    parts.append('</kml>')

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    return output_path


def write_gpx(passage: dict, output_path: str) -> str:
    """Write a GPX 1.1 route file. Returns the path.

    GPX 1.1 has two ways to express a route:
      - <wpt> elements (individual named waypoints, NOT connected)
      - <rte> with child <rtept> elements (a connected route in order)
    Chart plotters typically want the <rte>/<rtept> form for navigation.
    We emit BOTH so users can either browse named waypoints or follow the
    route, depending on plotter capability.
    """
    waypoints = passage["waypoints"]
    route_name = passage["passage"]["name"]
    origin = passage["passage"].get("origin", "")
    dest = passage["passage"].get("destination", "")
    total_nm = passage["passage"].get("total_nm", 0)
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    parts = ['<?xml version="1.0" encoding="UTF-8"?>']
    parts.append(
        '<gpx version="1.1" creator="sailbuild" '
        'xmlns="http://www.topografix.com/GPX/1/1" '
        'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
        'xsi:schemaLocation="http://www.topografix.com/GPX/1/1 '
        'http://www.topografix.com/GPX/1/1/gpx.xsd">'
    )
    parts.append('  <metadata>')
    parts.append(f'    <name>{xml_escape(route_name)} Route</name>')
    parts.append(
        f'    <desc>{xml_escape(origin)} to {xml_escape(dest)} '
        f'({total_nm:.0f} NM). Generated by sailbuild.</desc>'
    )
    parts.append(f'    <time>{now_iso}</time>')
    parts.append('  </metadata>')

    # Individual waypoints (browsable on any plotter)
    for wp in waypoints:
        wp_id = wp.get("id", "")
        wp_name = wp.get("name", "")
        cum_nm = wp.get("cum_nm", 0)
        parts.append(f'  <wpt lat="{wp["lat"]:.6f}" lon="{wp["lon"]:.6f}">')
        parts.append(f'    <name>{xml_escape(wp_id)}</name>')
        parts.append(f'    <cmt>{xml_escape(wp_name)}</cmt>')
        parts.append(f'    <desc>{xml_escape(wp_name)} — cum {cum_nm:.1f} NM</desc>')
        parts.append('  </wpt>')

    # Connected route
    parts.append('  <rte>')
    parts.append(f'    <name>{xml_escape(route_name)}</name>')
    parts.append(
        f'    <desc>{xml_escape(origin)} to {xml_escape(dest)}, '
        f'{total_nm:.0f} NM</desc>'
    )
    for wp in waypoints:
        wp_id = wp.get("id", "")
        wp_name = wp.get("name", "")
        parts.append(f'    <rtept lat="{wp["lat"]:.6f}" lon="{wp["lon"]:.6f}">')
        parts.append(f'      <name>{xml_escape(wp_id)}</name>')
        parts.append(f'      <cmt>{xml_escape(wp_name)}</cmt>')
        parts.append('    </rtept>')
    parts.append('  </rte>')

    parts.append('</gpx>')

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    return output_path


def write_route_files(passage: dict, output_dir: str) -> tuple:
    """Write both KML and GPX to output_dir. Returns (kml_path, gpx_path)."""
    os.makedirs(output_dir, exist_ok=True)
    base = _route_name_for_files(passage)
    kml_path = os.path.join(output_dir, f"{base}_Route.kml")
    gpx_path = os.path.join(output_dir, f"{base}_Route.gpx")
    write_kml(passage, kml_path)
    write_gpx(passage, gpx_path)
    return (kml_path, gpx_path)
